[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  NPM_FLAGS = "--no-optional"

# Production context
[context.production.environment]
  NODE_ENV = "production"
  ENVIRONMENT = "production"

# Preview context for pull requests
[context.deploy-preview.environment]
  NODE_ENV = "production"
  ENVIRONMENT = "preview"

# Branch deploys
[context.branch-deploy.environment]
  NODE_ENV = "production"
  ENVIRONMENT = "staging"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "X-Requested-With, Content-Type, Authorization"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Redirects
[[redirects]]
  from = "/docs"
  to = "/"
  status = 302

[[redirects]]
  from = "/healthz"
  to = "/api/health"
  status = 200

# Functions
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Edge functions for API routes
[[edge_functions]]
  function = "api"
  path = "/api/*"

# Form handling (if needed)
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true

# Environment variables template
[template.environment]
  DATABASE_URL = "Your PostgreSQL database URL"
  OPENAI_API_KEY = "Your OpenAI API key"
  SUPABASE_URL = "Your Supabase project URL"
  SUPABASE_ANON_KEY = "Your Supabase anonymous key"
  NEXTAUTH_SECRET = "Your NextAuth secret"
  NEXTAUTH_URL = "Your deployment URL"